
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salsabila Putri Ray
 */
public class menu extends javax.swing.JFrame {
    String str, str1, str2;
int choice,h,z,pin=1234,counter=0,a=3;
int t,s,tab=50000;

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        transfer = new javax.swing.JButton();
        penarikan = new javax.swing.JButton();
        setor = new javax.swing.JButton();
        bantuan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        saldo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Moon Flower Bold", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Keluar");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 460, 90, 50);

        jLabel7.setFont(new java.awt.Font("Moon Flower Bold", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bantuan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 330, 90, 50);

        jLabel6.setFont(new java.awt.Font("Moon Flower Bold", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Penyetoran");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 200, 110, 50);

        jLabel5.setFont(new java.awt.Font("Moon Flower Bold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Penarikan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 460, 100, 50);

        jLabel4.setFont(new java.awt.Font("Moon Flower Bold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transfer");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 330, 90, 50);

        jLabel3.setFont(new java.awt.Font("Moon Flower Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cek Saldo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 200, 110, 50);

        jLabel2.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("TRANSAKSI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 60, 220, 80);

        transfer.setText(">");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });
        getContentPane().add(transfer);
        transfer.setBounds(380, 320, 70, 60);

        penarikan.setText(">");
        penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penarikanActionPerformed(evt);
            }
        });
        getContentPane().add(penarikan);
        penarikan.setBounds(380, 450, 70, 60);

        setor.setText("<");
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        getContentPane().add(setor);
        setor.setBounds(30, 190, 70, 60);

        bantuan.setText("<");
        bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bantuanActionPerformed(evt);
            }
        });
        getContentPane().add(bantuan);
        bantuan.setBounds(30, 320, 70, 60);

        keluar.setText("<");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(30, 450, 70, 60);

        saldo.setText(">");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        getContentPane().add(saldo);
        saldo.setBounds(380, 190, 70, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lake-night-moon-mountains-free.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 640);

        setSize(new java.awt.Dimension(509, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab); //informasi saldo
    z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI",
    JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
    if (z==1){
    JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BNI, ambil kartu ATM Anda.");
System.exit(0);}
    }//GEN-LAST:event_saldoActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        // TODO add your handling code here:
         str2 = JOptionPane.showInputDialog(null,"Masukkan nomor rekening tujuan : " );
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah transfer : " );
        h=JOptionPane.showConfirmDialog(null,"Anda berhasil melakukan transfer pada nomer rekening :"+str2+" Sebesar : "+str1,"Anda yakin?",
                JOptionPane.YES_NO_OPTION, 3);
t = Integer.parseInt(str1);
transfer mengambil = new transfer();
mengambil.transfer(tab,t);
tab =mengambil.getsaldo();

    z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI",
JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
    if (z==1){
    JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BNI, ambil kartu ATM Anda.");
System.exit(0);}
    }//GEN-LAST:event_transferActionPerformed

    private void penarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penarikanActionPerformed
        // TODO add your handling code here:
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan
t = Integer.parseInt(str1);
tarik mengambil = new tarik();
mengambil.ambil(tab,t);
tab =mengambil.getsaldo();

    z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI",
JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
    if (z==1){
    JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BNI, ambil kartu ATM Anda.");
System.exit(0);}
    }//GEN-LAST:event_penarikanActionPerformed

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        // TODO add your handling code here:
         str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung
s = Integer.parseInt(str1);
setor hasil = new setor();
hasil.menabung(tab, s);
tab =hasil.getsaldo();

    z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI",
JOptionPane.YES_NO_OPTION, 3);
    if (z==1){
    JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BNI, ambil kartu ATM Anda.");
System.exit(0);}
    }//GEN-LAST:event_setorActionPerformed

    private void bantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bantuanActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi\n[1] Masukkan PIN dengan benar\n[2] Bertransaksilah dengan benar sesuai pilihan\n[3] Gunakan Uang sesuai kebutuhan "
            + "dan rajinlah menabung\n ","INFO",1);
    }//GEN-LAST:event_bantuanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
    z=JOptionPane.showConfirmDialog(null,"Anda ingin keluar?","Keluar", JOptionPane.YES_NO_OPTION, 0);
if (z==0){
    JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BNI, ambil kartu ATM Anda");
System.exit(0);

    }//GEN-LAST:event_keluarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bantuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton keluar;
    private javax.swing.JButton penarikan;
    private javax.swing.JButton saldo;
    private javax.swing.JButton setor;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables
}
